SELECT
    MANUFACTURER.COMPANY,
    COUNT(DISTINCT PRODUCT.WARE) AS Produced,
    COUNT(DISTINCT MATERIAL.WARE) AS Consumed
FROM MANUFACTURER
         JOIN PRODUCT ON MANUFACTURER.RECIPE_ID = PRODUCT.RECIPE_ID
         LEFT JOIN MATERIAL ON MANUFACTURER.RECIPE_ID = MATERIAL.RECIPE_ID
GROUP BY MANUFACTURER.COMPANY
HAVING Produced > Consumed
ORDER BY COMPANY ASC;
