SELECT COMPANY
FROM MANUFACTURER, PRODUCT
WHERE MANUFACTURER.RECIPE_ID = PRODUCT.RECIPE_ID
GROUP BY MANUFACTURER.COMPANY, PRODUCT.WARE
HAVING COUNT(DISTINCT MANUFACTURER.RECIPE_ID) > 2
ORDER BY MANUFACTURER.COMPANY ASC;
