SELECT COMPANY
FROM MANUFACTURER, PRODUCT, CATEGORY
WHERE MANUFACTURER.RECIPE_ID = PRODUCT.RECIPE_ID
  AND PRODUCT.WARE = CATEGORY.WARE
  AND (	CLASS = 'Fuel'
    OR	CLASS = 'Food'
    OR	CLASS = 'Mineral')
GROUP BY COMPANY
HAVING COUNT(DISTINCT CLASS) = 4
ORDER BY COMPANY ASC
