SELECT COMPANY, GROUP_CONCAT(DISTINCT mat.CLASS) as MATERIAL, GROUP_CONCAT(DISTINCT prod.CLASS) as PRODUCT
FROM MANUFACTURER
         JOIN PRODUCT ON MANUFACTURER.RECIPE_ID = PRODUCT.RECIPE_ID
         JOIN CATEGORY prod ON PRODUCT.WARE = prod.WARE
         LEFT JOIN MATERIAL ON MANUFACTURER.RECIPE_ID = MATERIAL.RECIPE_ID
         LEFT JOIN CATEGORY mat ON MATERIAL.WARE = mat.WARE
GROUP BY COMPANY
ORDER BY COMPANY ASC
