SELECT DISTINCT MANUFACTURER.COMPANY, PRODUCT.WARE
FROM MANUFACTURER
         JOIN PRODUCT
              ON MANUFACTURER.RECIPE_ID == PRODUCT.RECIPE_ID
JOIN CATEGORY
ON PRODUCT.WARE == CATEGORY.WARE
WHERE CATEGORY.CLASS == 'Raw food'
ORDER BY PRODUCT.WARE, MANUFACTURER.COMPANY ASC;
