SELECT DISTINCT PRODUCT.WARE
FROM PRODUCT
         JOIN MATERIAL
              ON PRODUCT.RECIPE_ID == MATERIAL.RECIPE_ID
JOIN CATEGORY
ON MATERIAL.WARE == CATEGORY.WARE
WHERE CATEGORY.CLASS == 'Mineral'
ORDER BY PRODUCT.WARE ASC;
