SELECT DISTINCT MANUFACTURER.COMPANY
FROM MANUFACTURER
         JOIN PRODUCT
              ON MANUFACTURER.RECIPE_ID == PRODUCT.RECIPE_ID
JOIN CATEGORY
ON PRODUCT.WARE == CATEGORY.WARE
WHERE CATEGORY.CLASS == 'Fuel'
INTERSECT
SELECT DISTINCT MANUFACTURER.COMPANY
FROM MANUFACTURER
         JOIN PRODUCT
              ON MANUFACTURER.RECIPE_ID == PRODUCT.RECIPE_ID
JOIN CATEGORY
ON PRODUCT.WARE == CATEGORY.WARE
WHERE CATEGORY.CLASS == 'Food';
