SELECT DISTINCT m1.COMPANY
FROM MANUFACTURER m1, PRODUCT p1, CATEGORY c1, MANUFACTURER m2, PRODUCT p2, CATEGORY c2
WHERE 	m1.RECIPE_ID == p1.RECIPE_ID AND p1.WARE == c1.WARE
	AND m2.RECIPE_ID == p2.RECIPE_ID AND p2.WARE == c2.WARE
	AND m1.COMPANY == m2.COMPANY AND c1.CLASS == c2.CLASS AND c1.WARE != c2.WARE
ORDER BY m1.COMPANY ASC;
