SELECT PRODUCT.WARE
FROM PRODUCT,
     (
         SELECT WARE,
                AVG(PRICE) as AVGPRICE
         FROM PRODUCT
         GROUP BY WARE
     ) SUB
WHERE PRODUCT.WARE = SUB.WARE
ORDER BY SUB.AVGPRICE DESC
    LIMIT 1
