SELECT DISTINCT COMPANY, CLASS
FROM MANUFACTURER OG_M, PRODUCT, CATEGORY OG_C
WHERE PRODUCT.RECIPE_ID = OG_M.RECIPE_ID
  AND PRODUCT.WARE = OG_C.WARE
  AND NOT EXISTS (SELECT 1 FROM CATEGORY SUB_C WHERE SUB_C.CLASS = OG_C.CLASS
                                                 AND NOT EXISTS (SELECT 1 FROM PRODUCT, MANUFACTURER WHERE PRODUCT.RECIPE_ID = MANUFACTURER.RECIPE_ID
                                                                                                       AND WARE = SUB_C.WARE AND COMPANY = OG_M.COMPANY))
ORDER BY CLASS
