SELECT MANUFACTURER.RECIPE_ID, COMPANY, GROUP_CONCAT(DISTINCT MATERIAL.WARE) AS MATERIAL, GROUP_CONCAT(DISTINCT PRODUCT.WARE) AS PRODUCT, SUM(DISTINCT PRICES.TOTAL)
FROM MANUFACTURER
         JOIN PRODUCT ON PRODUCT.RECIPE_ID = MANUFACTURER.RECIPE_ID
         JOIN (SELECT RECIPE_ID, WARE, AMOUNT * PRICE AS TOTAL FROM PRODUCT) PRICES ON PRICES.RECIPE_ID = MANUFACTURER.RECIPE_ID AND PRICES.WARE = PRODUCT.WARE
         LEFT JOIN MATERIAL ON MATERIAL.RECIPE_ID = MANUFACTURER.RECIPE_ID
GROUP BY MANUFACTURER.RECIPE_ID, COMPANY
ORDER BY COMPANY
