SELECT WARES.WARE, GROUP_CONCAT(MATERIALS.PACKS, ' || ') AS MATERIALS_PACKS, BYPRODUCTS.PACKS
FROM (SELECT DISTINCT WARE FROM CATEGORY) WARES
         JOIN (SELECT DISTINCT CATEGORY.WARE, COALESCE(GROUP_CONCAT(DISTINCT MATERIAL.WARE), 'Nothing') AS PACKS
               FROM CATEGORY
                        JOIN PRODUCT ON PRODUCT.WARE = CATEGORY.WARE
                        LEFT JOIN MATERIAL ON MATERIAL.RECIPE_ID = PRODUCT.RECIPE_ID
               GROUP BY CATEGORY.WARE, PRODUCT.RECIPE_ID) MATERIALS ON MATERIALS.WARE = WARES.WARE
         LEFT JOIN (SELECT DISTINCT CATEGORY.WARE, GROUP_CONCAT(DISTINCT SUB.WARE) AS PACKS
                    FROM CATEGORY
                             JOIN PRODUCT ON PRODUCT.WARE = CATEGORY.WARE
                             JOIN PRODUCT SUB ON SUB.RECIPE_ID = PRODUCT.RECIPE_ID AND SUB.WARE != CATEGORY.WARE
                    GROUP BY CATEGORY.WARE) BYPRODUCTS ON BYPRODUCTS.WARE = WARES.WARE
GROUP BY WARES.WARE
