SELECT COMPANY, GROUP_CONCAT(DISTINCT WARE ORDER BY WARE ASC)
FROM MANUFACTURER, PRODUCT,
     (SELECT COUNT(DISTINCT WARE) AS AMOUNT FROM MANUFACTURER, PRODUCT WHERE MANUFACTURER.RECIPE_ID = PRODUCT.RECIPE_ID GROUP BY COMPANY) SUB
WHERE MANUFACTURER.RECIPE_ID = PRODUCT.RECIPE_ID
GROUP BY COMPANY
HAVING COUNT(DISTINCT WARE) = MAX(SUB.AMOUNT)
ORDER BY COMPANY ASC
